apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit262-group4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit262-group4
  template:
    metadata:
      labels:
        app: cit262-group4
    spec:
      containers:
      - name: cit262-group4
        image: gcr.io/potent-galaxy-274115/cit262-group4
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: ".5"
            memory: "500Mi"
          requests:
            cpu: ".25"
            memory: "250Mi"
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cit262-group3-service
spec:
  selector:
    app: cit262-group4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cit262-group4-loadbalancer
spec:
  selector:
    app: cit262-group4
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
   
